name: publish to itch.io

on:
  release:
    types: [published]

jobs:     
  release_html:
      runs-on: ubuntu-latest
      steps:
        - name: download HTML5
          id: download-html
          uses: dsaltares/fetch-gh-release-asset@master
          with:
            version: "latest"
            file: HTML5.zip
            token: "${{ secrets.GITHUB_TOKEN }}"
        - name: deploy to itch.io (HTML5)
          uses: josephbmanley/butler-publish-itchio-action@master
          env:
            BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
            CHANNEL: html
            ITCH_GAME: godot-space-shooter
            ITCH_USER: iznaut
            PACKAGE: HTML5.zip
            VERSION: ${{ steps.download-html.outputs.version }}
